import { HeroClassConfig, HeroClassType } from '../types/game';

export const HERO_CLASSES: Record<HeroClassType, HeroClassConfig> = {
  warrior: {
    id: 'warrior',
    name: 'Knight of Ares',
    title: 'Vanguard of War',
    description: 'A heavily armored gladiator favored by the God of War. Masters heavy blade cleaves, defensive shield dashes, and furious whirlwind strikes.',
    avatarColor: '#ef4444',
    baseHp: 160,
    baseMana: 60,
    baseStamina: 100,
    baseSpeed: 3.2,
    baseAttackDamage: 24,
    baseDefense: 8,
    weaponType: 'sword',
    skill1: {
      name: 'Shield Rush',
      description: 'Slam forward with a spiked aegis, dealing 35 damage, knocking enemies back and stunning them for 1.2s.',
      cooldown: 5.0,
      manaCost: 20,
      icon: 'Shield',
    },
    skill2: {
      name: 'Cyclone Cleave',
      description: 'Spin with your broadsword in a 360-degree arc, hitting all surrounding foes for 50 physical damage.',
      cooldown: 7.0,
      manaCost: 30,
      icon: 'RotateCw',
    },
    ultimate: {
      name: 'Spartan Wrath',
      description: 'Call upon Ares: +60% Damage, +40% Speed, 25% Lifesteal, and crowd-control immunity for 8 seconds.',
      cooldown: 25.0,
      manaCost: 50,
      icon: 'Flame',
    },
  },
  mage: {
    id: 'mage',
    name: 'Sorceress of Hecate',
    title: 'Mistress of the Arcane',
    description: 'A master of primordial elements and mystic sorcery. Obliterates foes from a distance with homing arcane bolts, freezing frost novae, and devastating meteors.',
    avatarColor: '#8b5cf6',
    baseHp: 100,
    baseMana: 160,
    baseStamina: 80,
    baseSpeed: 3.0,
    baseAttackDamage: 28,
    baseDefense: 3,
    weaponType: 'staff',
    skill1: {
      name: 'Frost Nova',
      description: 'Release a freezing ring of ice that deals 30 frost damage and freezes all surrounding enemies for 2.5s.',
      cooldown: 6.0,
      manaCost: 35,
      icon: 'Snowflake',
    },
    skill2: {
      name: 'Aether Blink',
      description: 'Teleport instantly toward your cursor / facing direction, leaving an electric shockwave that zaps enemies.',
      cooldown: 5.0,
      manaCost: 25,
      icon: 'Zap',
    },
    ultimate: {
      name: 'Meteor Cataclysm',
      description: 'Summon 5 fiery meteors from the heavens that crash into target area, dealing massive 120 fire explosion damage.',
      cooldown: 28.0,
      manaCost: 70,
      icon: 'Sparkles',
    },
  },
  ranger: {
    id: 'ranger',
    name: 'Huntress of Artemis',
    title: 'Shadow of the Crescent Bow',
    description: 'A swift and lethal huntress of the moonlit wilds. Fires rapid piercing arrows, deploys crippling snares, and rains death from above.',
    avatarColor: '#10b981',
    baseHp: 120,
    baseMana: 100,
    baseStamina: 120,
    baseSpeed: 3.6,
    baseAttackDamage: 22,
    baseDefense: 5,
    weaponType: 'bow',
    skill1: {
      name: 'Shadow Decoy Dash',
      description: 'Tumble backwards while leaving an illusory decoy that taunts nearby monsters and explodes for 40 damage.',
      cooldown: 4.5,
      manaCost: 20,
      icon: 'Footprints',
    },
    skill2: {
      name: 'Arrow Volley',
      description: 'Fire a fan of 5 piercing moonlight arrows that poison and shred through lines of enemies for 35 damage each.',
      cooldown: 6.5,
      manaCost: 30,
      icon: 'Compass',
    },
    ultimate: {
      name: 'Moonlight Rain',
      description: 'Unleash a torrential barrage of 15 lunar arrows over target area, pinning down monsters and dealing 150 damage over 3s.',
      cooldown: 24.0,
      manaCost: 55,
      icon: 'Target',
    },
  },
};
